"""empty message

Revision ID: d71eae5e4f8f
Revises: 9903cf2d86cc
Create Date: 2020-02-24 14:51:34.591393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71eae5e4f8f'
down_revision = '9903cf2d86cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('img', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'img')
    # ### end Alembic commands ###
