"""empty message

Revision ID: defa0c585f55
Revises: d71eae5e4f8f
Create Date: 2020-03-01 16:14:37.822135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'defa0c585f55'
down_revision = 'd71eae5e4f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('img', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
